package hksarg.sgil.constant;

public class EmailTemplate {

	public final static String PORTAL_USER_ACTIVE = "PORTAL_USER_ACTIVE";
	public final static String DISCUSSION_GROUP_CREATE_REQUEST = "DISCUSSION_GROUP_CREATE_REQUEST";
	public final static String DISCUSSION_GROUP_CREATE_ACCEPT = "DISCUSSION_GROUP_CREATE_ACCEPT";
	public final static String DISCUSSION_GROUP_CREATE_REJECT = "DISCUSSION_GROUP_CREATE_REJECT";
	public final static String DISCUSSION_GROUP_INVITE = "DISCUSSION_GROUP_INVITE";
	public final static String DISCUSSION_GROUP_MEMBER_JOIN_ACCEPT = "DISCUSSION_GROUP_MEMBER_JOIN_ACCEPT";
	public final static String DISCUSSION_GROUP_MEMBER_JOIN_REJECT = "DISCUSSION_GROUP_MEMBER_JOIN_REJECT";
	public final static String DISCUSSION_GROUP_MEMBER_JOIN_REQUEST = "DISCUSSION_GROUP_MEMBER_JOIN_REQUEST";
	public final static String DISCUSSION_GROUP_MEMBER_REMOVE = "DISCUSSION_GROUP_MEMBER_REMOVE";
	public final static String DISCUSSION_GROUP_MEMBER_LEAVE = "DISCUSSION_GROUP_MEMBER_LEAVE";
	public final static String DISCUSSION_POST_SUBSCRIBE = "DISCUSSION_POST_SUBSCRIBE";
	public final static String SSA_SUBSCRIBE = "SSA_SUBSCRIBE";
	public final static String THREAT_SUBSCRIBE = "CTI_SUBSCRIBE";
}
